// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Constance.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WS.Data {

  /// <summary>Holder for reflection information generated from Constance.proto</summary>
  public static partial class ConstanceReflection {

    #region Descriptor
    /// <summary>File descriptor for Constance.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConstanceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Db25zdGFuY2UucHJvdG8SB1dTLkRhdGEaEERhdGFMZXR0ZXIucHJvdG8a",
            "D0RhdGFQaWVjZS5wcm90bxoPRGF0YUxldmVsLnByb3RvIoIBCglDb25zdGFu",
            "Y2USJwoKbGV0dGVyTGlzdBgBIAMoCzITLldTLkRhdGEuRGF0YUxldHRlchIl",
            "CglwaWVjZUxpc3QYAiADKAsyEi5XUy5EYXRhLkRhdGFQaWVjZRIlCglsZXZl",
            "bExpc3QYAyADKAsyEi5XUy5EYXRhLkRhdGFMZXZlbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WS.Data.DataLetterReflection.Descriptor, global::WS.Data.DataPieceReflection.Descriptor, global::WS.Data.DataLevelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WS.Data.Constance), global::WS.Data.Constance.Parser, new[]{ "LetterList", "PieceList", "LevelList" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Constance : pb::IMessage<Constance> {
    private static readonly pb::MessageParser<Constance> _parser = new pb::MessageParser<Constance>(() => new Constance());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Constance> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WS.Data.ConstanceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Constance() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Constance(Constance other) : this() {
      letterList_ = other.letterList_.Clone();
      pieceList_ = other.pieceList_.Clone();
      levelList_ = other.levelList_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Constance Clone() {
      return new Constance(this);
    }

    /// <summary>Field number for the "letterList" field.</summary>
    public const int LetterListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::WS.Data.DataLetter> _repeated_letterList_codec
        = pb::FieldCodec.ForMessage(10, global::WS.Data.DataLetter.Parser);
    private readonly pbc::RepeatedField<global::WS.Data.DataLetter> letterList_ = new pbc::RepeatedField<global::WS.Data.DataLetter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WS.Data.DataLetter> LetterList {
      get { return letterList_; }
    }

    /// <summary>Field number for the "pieceList" field.</summary>
    public const int PieceListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::WS.Data.DataPiece> _repeated_pieceList_codec
        = pb::FieldCodec.ForMessage(18, global::WS.Data.DataPiece.Parser);
    private readonly pbc::RepeatedField<global::WS.Data.DataPiece> pieceList_ = new pbc::RepeatedField<global::WS.Data.DataPiece>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WS.Data.DataPiece> PieceList {
      get { return pieceList_; }
    }

    /// <summary>Field number for the "levelList" field.</summary>
    public const int LevelListFieldNumber = 3;
    private static readonly pb::FieldCodec<global::WS.Data.DataLevel> _repeated_levelList_codec
        = pb::FieldCodec.ForMessage(26, global::WS.Data.DataLevel.Parser);
    private readonly pbc::RepeatedField<global::WS.Data.DataLevel> levelList_ = new pbc::RepeatedField<global::WS.Data.DataLevel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WS.Data.DataLevel> LevelList {
      get { return levelList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Constance);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Constance other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!letterList_.Equals(other.letterList_)) return false;
      if(!pieceList_.Equals(other.pieceList_)) return false;
      if(!levelList_.Equals(other.levelList_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= letterList_.GetHashCode();
      hash ^= pieceList_.GetHashCode();
      hash ^= levelList_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      letterList_.WriteTo(output, _repeated_letterList_codec);
      pieceList_.WriteTo(output, _repeated_pieceList_codec);
      levelList_.WriteTo(output, _repeated_levelList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += letterList_.CalculateSize(_repeated_letterList_codec);
      size += pieceList_.CalculateSize(_repeated_pieceList_codec);
      size += levelList_.CalculateSize(_repeated_levelList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Constance other) {
      if (other == null) {
        return;
      }
      letterList_.Add(other.letterList_);
      pieceList_.Add(other.pieceList_);
      levelList_.Add(other.levelList_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            letterList_.AddEntriesFrom(input, _repeated_letterList_codec);
            break;
          }
          case 18: {
            pieceList_.AddEntriesFrom(input, _repeated_pieceList_codec);
            break;
          }
          case 26: {
            levelList_.AddEntriesFrom(input, _repeated_levelList_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
